alt="Ahmed Mohamed Bussuri">

<h2>
Ahmed Mohamed Bussuri
</h2>

</div>




<div class="card">

<h3>Taariikh Nololeedka</h3>

<p>
Ahmed Mohamed Bussuri wuxuu ku dhashay degmada Boondheere,
degaan ahaan wuxuu kasoo jeedaa Hatimy, sanadkii 1972 Juun.
</p>

</div>





<div class="card">

<h3>Waxbarashada</h3>

<ul>

<li>Dugsiga hoose (1-4): Yasiin Cismaan</li>

<li>Dugsiga dhexe: Wiilwaal</li>

<li>Dugsiga Secondary: Bartamaha</li>

<li>
GCSE Mathematics & English -
Stratford College Newham Campus
</li>

<li>
SOAS University of London -
Global Diplomacy (Diplomacy in Modern World)

